import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CustomBox from "../components/customBox";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  info,
  media,
  widgets,
}: Readonly<{
  children: React.ReactNode;
  info: React.ReactNode;
  media: React.ReactNode;
  widgets: React.ReactNode;
}>) {
  return (
    <div>
      <div>
        <CustomBox children={info}></CustomBox>
        <CustomBox children={media}></CustomBox>
        <CustomBox children={widgets}></CustomBox>
      </div>
      <div className={inter.className}>{children}</div>
    </div>
  );
}
