import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {/* <Link href="/">Home</Link>
          <Link href="/contacts">Contacts</Link>
          <Link href="/login">Login</Link>
          <Link href="/register">Register</Link>
          <Link href="/forgot-password">Forgot Password</Link>
          <Link href="/users">Users</Link>
          <Link href="/products">Products</Link> */}
          </div>{children}</body>
    </html>
  );
}
